name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: "*/55 * * * *" # every 55th minute

jobs:
  ##############################################################################
  wake-up:
    runs-on: ubuntu-latest

    steps:
      - run: curl -X POST --fail-with-body --retry 5 --retry-all-errors ${{ secrets.WEBHOOK_URL }}
