name: test

on:
  - push
  - pull_request

jobs:
  ##############################################################################
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: Byndyusoft/node-reusable-workflows/.github/actions/install@master
        with:
          node-version: lts/*

      - run: yarn run build

      - run: yarn run lint
